name: Azure Data Platform CI

on:
  pull_request:

jobs:
  branch-validation:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get head and base branch name
        id: getBranchName
        run: |
          head_branch=${GITHUB_HEAD_REF##*/}
          base_branch=${GITHUB_BASE_REF##*/}
          yq_deny_expression='.branches.'"${base_branch}"'.deny[] | select("'"${head_branch}"'" == .)'
          yq_allow_expression='.branches.'"${base_branch}"'.allow[] | select("'"${head_branch}"'" == .)'

          echo "::set-output name=yq_deny_expression::$yq_deny_expression"
          echo "::set-output name=yq_allow_expression::$yq_allow_expression"

          yq --help

      - name: Get Deny Rules
        id: getDenyRules
        uses: mikefarah/yq@v4.16.2
        with:
          cmd: yq eval '${{ steps.getBranchName.outputs.yq_deny_expression }}' .github/branch-rules.yml

      - name: List Deny Rule
        run: |
          echo ${{ steps.getDenyRules.outputs.result }}

      - name: Get Allow Rules
        id: getAllowRules
        uses: mikefarah/yq@v4.16.2
        with:
          cmd: yq eval '${{ steps.getBranchName.outputs.yq_allow_expression }}' .github/branch-rules.yml

      - name: List Allow Rule
        run: |
          echo ${{ steps.getAllowRules.outputs.result }}

  # adf-validation:
  #   runs-on: ubuntu-20.04
  #   needs: branch-validation

  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Validate the ADF
  #     - name: Validate ADF
  #       id: validate_adf
  #       uses: Azure/data-factory-validate-action@v1.1.5
  #       with:
  #         path: ./adf
  #         id: ${{ secrets.ADF_INGESTION_RESOURCE_ID }}
